### ISSUE TITLE
"TypeError: Not bool" on the initial insert

### ISSUE THREAD

**Issue by taurus-forever** [roman-right/AnnaDB#17]
Hi,

Please find the traceback for the crash on the very first insert into AnnaDB:
https://gist.github.com/taurus-forever/56492ae09c13b94e1a4788241d432a34

The command was copied from the documentation:
https://annadb.dev/documentation/insert/#example

**Comment by roman-right** [comment]
Hi @taurus-forever 

Thank you for the issue!
There is a typo in the query. Please, use `b|true|` instead of `b|True|`. Python syntax sneaked in :)
I'll fix the doc soon

**Comment by roman-right** [comment]
The doc is fixed.

**Comment by taurus-forever** [comment]
The fix is confirmed. Resolved. Tnx!
